version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

  go_service:
    restart: always
    build:
      context: ./hello-world/src
    container_name: go_service
    depends_on:
      - mosquitto
    volumes:
      - ./hello-world/src:/app
      - ./hello-world/src/config:/app/config
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto:1883
    networks:
      - mqtt_network

networks:
  mqtt_network: